META_ARC: "siamrpn_alex_dwxcorr"

BACKBONE:
    TYPE: "alexnet"
    KWARGS:
        width_mult: 1.0   
    PRETRAINED: 'pretrained_models/alexnet-bn.pth'
    TRAIN_LAYERS: ['layer4', 'layer5']
    TRAIN_EPOCH: 10
    LAYERS_LR: 1.0

ANCHOR:
    STRIDE: 8
    RATIOS: [0.33, 0.5, 1, 2, 3]
    SCALES: [8]
    ANCHOR_NUM: 5

TRACK:
    PENALTY_K: 0.16
    WINDOW_INFLUENCE: 0.40
    LR: 0.30
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 0
    CONTEXT_AMOUNT: 0.5

TRAIN:
    EPOCH: 50
    NUM_WORKERS: 1
    BATCH_SIZE: 128
    BASE_SIZE: 0
    OUTPUT_SIZE: 17
    BASE_LR: 0.005
    LAMBDA: 1.2


DATASET:
    NAMES:
    - 'VID'
    - 'YOUTUBEBB'

    TEMPLATE:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    GRAY: 0.0
